[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pump_fun = "9MHPjXpZXgJrB4NiJVFStE5qy7Nqp7yaYpaqNe5jNfMw"

[programs.devnet]
pump_fun = "9MHPjXpZXgJrB4NiJVFStE5qy7Nqp7yaYpaqNe5jNfMw"

[programs.mainnet]
pump_fun = "9MHPjXpZXgJrB4NiJVFStE5qy7Nqp7yaYpaqNe5jNfMw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./keys/test-kp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
