[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pump_fun = "DkgjYaaXrunwvqWT3JmJb29BMbmet7mWUifQeMQLSEQH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./keys/test-kp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
